### ISSUE TITLE
777 must be file permisions

### ISSUE THREAD

**Issue by Rolilink** [joho/7XX-rfc#140]
;)!

**Comment by shamoons** [comment]
+1

**Comment by ppumkin** [comment]
+1

**Comment by POPSuL** [comment]
:+1:

**Comment by joho** [comment]
This idea I like, but i just can't home in on the right wording.

**Comment by nextalias** [comment]
How about "All your files are belong to us" ?

**Comment by goodseller** [comment]
I get that it means :seven::seven::seven: lucky for my first insight. Google say so too:
http://www.google.com/search?q=777+lucky :ghost:

**Comment by dennis-learningpool** [comment]
+1

**Comment by pjdelport** [comment]
@joho: How about something like "777 - Wrong file permission"?

That seems to go well with the the theme of "77X - Predictable Problems".
