### ISSUE TITLE
More description

### ISSUE THREAD

**Issue by dptole** [joho/7XX-rfc#158]
Hi guys, loved this repo!

I've create [this github page](http://dptole.github.io/httpstatus.es/) based on [this repo](https://github.com/citricsquid/httpstatus.es) and I wanted to add the **7xx developer errors** range on it. But in order to do that I need more description of each error code. I'll see what I can add to help.
What do you think?

**Comment by joho** [comment]
As luck would have it, I'm about to go on annual leave - I should use some of that time to tidy up this repo.
