### ISSUE TITLE
Stoned exists, but not high

### ISSUE THREAD

**Issue by panamaprophet** [joho/7XX-rfc#181]
I suppose it must be like this

762 - Stoned
763 - Too high

**Comment by stendarr** [comment]
I don' think _high_  is a good thing in the 76x range, since it is specified as *substance affected developer*. _Stoned_ describes the substance, whereas _high_ doesn't.

**Comment by panamaprophet** [comment]
I disagree, because there are two different states of mind based on a subject: one called "stoned" (when you get stuck to the couch) and another one is "high" (when you feeling yourself higher - uplifting and energetic). of course, you can simply google about it)

Anyway, dont wanna be a wet blanket man, lol

**Comment by stendarr** [comment]
I thought _stoned_ was for pot only. Well, the more you know, I guess. 
But your suggestion still leads to other problems: 
What will happen with the already taken 763? 
Do you want to change stoned to high?
