### ISSUE TITLE
Restriction of the internet due to unqualified politicians?

### ISSUE THREAD

**Issue by danwdart** [joho/7XX-rfc#199]
It's not copyright, but a government wanted to restrict it for some nonsense reason and had no idea how to.

See: sopa, cispa, net neutrality, cookie laws, link tax, etc.

Come to think of it, wasn't that an official code?

**Comment by Piskvor** [comment]
Reality exceeds fiction: https://en.wikipedia.org/wiki/HTTP_451

**Comment by danwdart** [comment]
That's what it was... sad times.

**Comment by yarooze** [comment]
Applied even for this Repository: https://www.linuxinsider.com/story/86154.html

**Comment by danwdart** [comment]
Gosh, the US is ridiculous.

**Comment by virtadpt** [comment]
Truer words have seldom been said.

**Comment by AsParallel** [comment]
I guess it's just the US, if you ignore article xiii and the icann rate hike deregulation.

**Comment by danwdart** [comment]
Sad times
It's a lot of sad times, they be blockin' and blockin' and blockin' and blockin' our net...
